# Generated by Django 5.1 on 2025-03-08 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collaboration', '0001_initial'),
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborationrequest',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.project'),
        ),
    ]
